[versions]
agp = "7.0.4"
sdk-min = "21"
sdk-target = "30"
sdk-compile = "31"
buildTools = "31.0.0"
maven-publish = "0.18.0"
kotlin = "1.5.31"
coroutines = "1.5.2"
compose = "1.0.5"
androidx-activity = "1.4.0"
accompanist = "0.20.3"
coil = "1.4.0"
jUnit = "4.13.2"
truth = "1.1.3"
testExt = "1.1.1"
espresso = "3.2.0"

[libraries]
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
jUnit = { module = "junit:junit", version.ref = "jUnit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
testExt = { module = "androidx.test.ext:junit", version.ref = "testExt" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[bundles]
compose = ["compose-foundation", "compose-material"]
accompanist = ["accompanist-insets", "accompanist-pager"]
