name: Publish

on:
  push:
    branches: [ main ]
    paths:
      - 'zoomable/**'
      - '*.kts'
      - '*.properties'
      - 'gradle/**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        run: sh -c "mkdir -p ~/.gradle && echo '${GRADLE_PROPERTIES}' > ~/.gradle/gradle.properties"

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Publish
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
        run: ./gradlew --no-daemon publish
